# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaultDocker
  docker:
      - image: circleci/node:13.8.0
jobs:
  build:
    <<: *defaultDocker
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    <<: *defaultDocker
    steps:
      - run: npm i
      - run: npm run test
  analyse:
    <<: *defaultDocker
    steps: 
      - run: npm audit  
workflows:
  pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse:
          requires:
            - test      